In [1]:
from explore import explore_tsv, months, paths, top_from_search, top_articles

In [2]:
f = paths[1]
              
df = explore_tsv(f)
top_from_search(df)[:25]

                                            n
curr
Mouvement_des_Gilets_jaunes            356218
Freddie_Mercury                        269269
La_Vérité_sur_l'affaire_Harry_Quebert  268130
Emmanuel_Macron                        262944
Mai_68                                 262693
Miss_France                            221649
Noël                                   219497
Affaire_Dupont_de_Ligonnès             219316
Alexandre_Benalla                      203065
Maria_Pacôme                           201234
Christophe_Castaner                    180895
Bigflo_et_Oli                          179712
Miss_France_2019                       170748
Jenifer                                163328
Jason_Momoa                            156276
Saint-Nicolas_(fête)                   153864
Père_Noël                              149111
Impôt_de_solidarité_sur_la_fortune     148980
Bird_Box_(film)                        147601
Ballon_d'or                            146974
Lionel_Messi                           145729
Kylian_Mbappé                          145281
Arc_de_triomphe_de_l'Étoile            145112
Cristiano_Ronaldo                      143662
Angèle_(chanteuse)                     143405

In [3]:
top_articles(df)[:25]

                                                          n
curr
-                                                   1081497
France                                               643807
Mouvement_des_Gilets_jaunes                          482648
Freddie_Mercury                                      374312
Emmanuel_Macron                                      367666
Technologies_de_l'information_et_de_la_communic...   367010
Signaux_faibles                                      334941
Comptabilité                                         308584
La_Vérité_sur_l'affaire_Harry_Quebert                305413
Mai_68                                               303086
Noël                                                 277073
Miss_France                                          265673
Affaire_Dupont_de_Ligonnès                           253819
Maria_Pacôme                                         251855
Kayden_Boche                                         239863
Alexandre_Benalla                                    238665
Miss_France_2019                                     233922
Christophe_Castaner                                  230869
Propylène_glycol                                     227278
Lionel_Messi                                         224165
Cristiano_Ronaldo                                    215816
Accueil                                              212479
George_H._W._Bush                                    209814
Jason_Momoa                                          209297
Bigflo_et_Oli                                        206687